name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[16.4,16.5)'

      - name: Build app for release
        run: msbuild Project64.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Package zip
        run: ./Source/Script/package_zip.cmd

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: project64.zip
          path: |
            project64.zip
